### ISSUE TITLE
Bug with pagination in production 

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para#25]
500 on table page

```
An ActionView::Template::Error occurred in my_component#show:

No route matches {:action=>"show", :component_id=>"my_component_slug", :controller=>"admin/my_component", :page=>nil}

app/views/admin/my_component/show.html.haml:4:in `_app_views_admin_my_component_show_html_haml___1398735354282324111_70013877212120'
```

Works in developement.

## EDIT NOTE :

Add to `config/environments/development.rb` : 

```ruby
config.cache_classes = true
```

Seems to be because routes context is the one of Para in the view, so the route is not found on the Para engine, because it only exists in the main app

**Comment by vala** [comment]
Actually, we'll still have a bug on custom components (i.e.: components
outside of Para)

*Gabriel Cardoso*
Glyph
+33 6 89 07 24 98 <+33689072498> / +33 9 53 55 22 91 <+33953552291>
31 rue raspail / 94200 Ivry Sur Seine
http://www.glyph.fr

2015-02-19 17:11 GMT+01:00 Gabriel Cardoso <notifications@github.com>:
