### ISSUE TITLE
500 after creating a Para:Page via admin interface

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para#26]
* I created a new component section from admin panel
* I added a new Page component, entered the name
* I filled up the form: title, slug and content
* I got an error when clicked "Save" but the page was correctly created

```
A NoMethodError occurred in page#update:

undefined method `path' for #<Para::Component::Page:0x007f5b1913d050>
```

**Comment by gabriel-cardoso** [comment]
Any way around in the meantime ?

**Comment by vala** [comment]
updating pages from the rails console ? :) @gabriel-cardoso

**Comment by gabriel-cardoso** [comment]
Updated para but problem is still here

**Comment by gabriel-cardoso** [comment]
Had to point `active_decorator` gem to `dev` branch to fix the issue...

**Comment by vala** [comment]
known issue, should be added to doc until PRs are merged into active decorator ... @gabriel-cardoso
