### ISSUE TITLE
Bug using selectize on HABTM relation

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para#34]
An error is raised when using `form.association :other_model, as: :selectize` in nested fields for `MyModel` and where `MyModel has_and_belongs_to_many :other_models`

Error is `Undefined method my_model_id for #<MyModel>`

**Comment by vala** [comment]
@zenati had the same issue on some projet, maybe he can remember how we fixed it, but it's all about reflection foreign_key detection, and is xana68/simple_form_extension related

**Comment by gabriel-cardoso** [comment]
Indeed. This is the commit in question https://github.com/xana68/simple_form_extension/commit/6a6ec60c4cb144a983ede2895f1aebf9646f9f99

**Comment by vala** [comment]
Is this still an issue @gabriel-cardoso ?

**Comment by gabriel-cardoso** [comment]
Don't think so
