### ISSUE TITLE
Add breadcrumbs

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para#36]
Could be nice to have breadcrumbs in edit pages so we can easily go back to index for example.

**Comment by gabriel-cardoso** [comment]
:up:

**Comment by vala** [comment]
Implemented in https://github.com/para-cms/para/commit/9f3b969d494e9aea92737bcbb4b36d34b084a59f

**Comment by vala** [comment]
please @gabriel-cardoso review, and @xana68 have a design check ;)

**Comment by xana68** [comment]
![capture d ecran 2015-12-03 a 15 17 56](https://cloud.githubusercontent.com/assets/686997/11562996/a5688178-99d1-11e5-8c4d-0d4efd1af38e.png)

What do you think ?

**Comment by vala** [comment]
Seems a good start but the colors don’t play well together.
Also, I dont understand why the « Produits » breadcrumb is gray

**Comment by xana68** [comment]
![capture d ecran 2015-12-04 a 12 32 04](https://cloud.githubusercontent.com/assets/686997/11588764/4504f46c-9a83-11e5-93c8-c7c220919d1d.png)

Better i think !

**Comment by vala** [comment]
I will try to pull and check when I can.

Can you give a wider screenshot next time ?
With the one you provided, this is hard to imagine how it looks inside the page.

**Comment by vala** [comment]
My first impression is that the new version doesn't wrap enough the breadcrumbs to make them explicit enough. I think I prefer the original (default bootstrap) design, which had a gray background that made the breadcrumbs more visible.

**Comment by xana68** [comment]
Now the breadcrumb is more like bootstrap and isn't on the bottom of the horizontal navbar.

![capture d ecran 2016-03-03 a 13 52 33](https://cloud.githubusercontent.com/assets/686997/13494847/37223692-e147-11e5-94f3-269c75ebcef1.png)

**Comment by vala** [comment]
:shipit:
