### ISSUE TITLE
`Para.my_component` crashes in prodution

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para#37]
Calling `Para.my_component` works in dev whereas it does not in production.

Note: `Para.components.my_component` works in both.

**Comment by vala** [comment]
`Para.my_component` should never work, for now please don't use it, I'll have to fix that

**Comment by vala** [comment]
After testing, this does not work in dev anymore. 

Closing for now, reopen if you need, providing more informations on how to reproduce the error
