### ISSUE TITLE
Enhanced crud index page

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para#41]
Users tend to type in search bar to create a new entry.

Ideas:

- [x] Placeholder in search bar
- [x] Put a create button in search results when no results
- [ ] Floating create button

**Comment by vala** [comment]
Added placeholder in search and create button in search results with :

https://github.com/para-cms/para/commit/1a936b4865a26562a5f6d609c1fe05cbb4efe36c
and
https://github.com/para-cms/para/commit/725d38627908353488507f9d4ea9a6ea1ec92ff2

Please review, design if needed and close @gabriel-cardoso @xana68

**Comment by gabriel-cardoso** [comment]
:+1: Works for me. 

Small bug when there is no create button (i.e.: SEO Tools/Sitemap)

![image](https://cloud.githubusercontent.com/assets/701338/11526572/9f12b10a-98db-11e5-929d-65ec0688f466.png)

In my own opinion, create button should be outside listing panel, floating in some way (in a bar or not)

**Comment by xana68** [comment]
The placeholder was to light so i change it by more darken color.

@gabriel-cardoso If i drop create button from the panel heading so there will never something in it.

**Comment by xana68** [comment]
https://github.com/para-cms/para/issues/22
