### ISSUE TITLE
Style new tab navigation in forms

### ISSUE THREAD

**Issue by vala** [para-cms/para#42]
I added a standard way to render a tabbed navigation inside the admin forms, see [the wiki for Customizing Forms](https://github.com/para-cms/para/wiki/Customizing-Forms#adding-tabs).

For now, the design is pretty ugly, but the navigation is visible. I tryed with a white version but it was almost invisible to the user.

<img width="1194" alt="capture d ecran 2015-11-29 a 17 58 44" src="https://cloud.githubusercontent.com/assets/792772/11458950/79b611c0-96cb-11e5-98b7-2dfc46428b1f.png">

The tabs are rendered with a combination of the [`Para::FormBuilder::Tabs`](https://github.com/para-cms/para/blob/09821a2fead5f348f7db9c554c01e63ae3794386/lib/para/form_builder/tabs.rb) mixin and the [tabs partial](https://github.com/para-cms/para/blob/master/app/views/para/form/_tabs.html.haml) allowing you to style it easily.

@xana68 can you try something to style those tabs ?

Thanks !

**Comment by xana68** [comment]
Do u like it ?

![capture d ecran 2015-12-01 a 13 14 46](https://cloud.githubusercontent.com/assets/686997/11500462/880cef7e-982d-11e5-9a09-eb830e32a3bc.png)

**Comment by vala** [comment]
No

**Comment by xana68** [comment]
So know yes :p

![capture d ecran 2015-12-01 a 13 28 02](https://cloud.githubusercontent.com/assets/686997/11500745/60c6f0fc-982f-11e5-962f-3abfedbd9eea.png)

**Comment by vala** [comment]
YES PAPA
