### ISSUE TITLE
Ideas for future developments

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para#44]
- [x] add a translations component with https://github.com/glyph-fr/i18n_admin
- [x] Dashboard
- [x] Roles plugin: manage groups, admin users and access (read & read/write)
- [ ] Integrate a file browser
- [ ] History of actions (could be displayed on dashboard)

**Comment by vala** [comment]
This small list represents quite a lot of work.

For the translations and roles plugins we should build them as external gems.

I started a dashboard view here : 7a2d0dedaf1ab2a5d0e95ed1246683be4a30a24c (merged in master) but is just meant to override the default behavior

**Comment by vala** [comment]
I'll close this issue and open two new issues for the File browser and Actions history
