### ISSUE TITLE
Styling page loading

### ISSUE THREAD

**Issue by vala** [para-cms/para#45]
In https://github.com/para-cms/para/commit/bd5a84badd55c3dfd1490a78de1c417dee13a209 I introduced an overlay and a spinner over the main content area whenever a classic turbolinks page loading or form submission occurs.

This fixes the general unresponse feeling when the action takes some time to run.

Please @xana68 review the design if it's ok for you.

**Note 1 :**

For the spinner I used the following generator : http://preloaders.net/en/circular
Using the "Instagram loading" model, with a 32x32 size (This size is reflected in the `para/admin/src/page-loading.sass` stylesheet, so you'll need to change it if you change the spinner size)

**Note 2 :**

I created a stylesheets folder at `para/admin/src` which is required by the `para/admin.sass` main stylesheet, and added my code into a new `para/admin/src/page-loading.sass`. Is this the right way to add styles for you ?

**Comment by gabriel-cardoso** [comment]
:+1: for the loader. No clue for **Note 2**

**Comment by xana68** [comment]
@vala I just put more opacity like .5 instead of .3 because i don't see the opacity very well. 

Note 2 : Good ! so i put few files in it :)
