### ISSUE TITLE
Server needs to be restarted when using `Para::Sti::RootModel`

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para#52]
When using a `Para::Sti::RootModel` in a nested model, the dropdown with the subclasses is empty when I edit some code in my app. Server needs to be restarted to correctly load the subclasses list.

**Comment by vala** [comment]
This was fixes when we added the `:nested_many` input the `:subclasses` option, which forces us to explicitly add subclasses to the dropdowns, and fixes this issue which was bound to Rails dev environment reloading strategy
